### PR TITLE
Zip Template

### PR DESCRIPTION
**Pull request by lemnet**
Please discard commit https://github.com/ridiculousfish/HexFiend/pull/217/commits/389d2e83bec71e57482bac84fafae35021fe98d1 , it's a mistake

### CODE REVIEW

**Comment by kainjow** [comment]
Please update the title to reflect for JPG deletion.

**Comment by lemnet** [comment]
The JPG deletion was a mistake...
As I said, please discard commit https://github.com/ridiculousfish/HexFiend/commit/389d2e83bec71e57482bac84fafae35021fe98d1

**Comment by kainjow** [comment]
Yes, but are you not able to update this PR's title, since it's now incorrect?

**Comment by lemnet** [comment]
OK, done

**Pull request merged**
